// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Minor.Dag21.CASServiceClient.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CursusInstantie
    {
        /// <summary>
        /// Initializes a new instance of the CursusInstantie class.
        /// </summary>
        public CursusInstantie() { }

        /// <summary>
        /// Initializes a new instance of the CursusInstantie class.
        /// </summary>
        public CursusInstantie(Cursus cursus, DateTime startdatum, int? cursusInstantieID = default(int?))
        {
            CursusInstantieID = cursusInstantieID;
            Cursus = cursus;
            Startdatum = startdatum;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursusInstantieID")]
        public int? CursusInstantieID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursus")]
        public Cursus Cursus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startdatum")]
        public DateTime Startdatum { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Cursus == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Cursus");
            }
        }
    }
}
