// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Minor.Dag21.CASServiceClient.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Cursus
    {
        /// <summary>
        /// Initializes a new instance of the Cursus class.
        /// </summary>
        public Cursus() { }

        /// <summary>
        /// Initializes a new instance of the Cursus class.
        /// </summary>
        public Cursus(int? cursusId = default(int?), string cursuscode = default(string), string titel = default(string), int? duur = default(int?))
        {
            CursusId = cursusId;
            Cursuscode = cursuscode;
            Titel = titel;
            Duur = duur;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursusId")]
        public int? CursusId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursuscode")]
        public string Cursuscode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "titel")]
        public string Titel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "duur")]
        public int? Duur { get; set; }

    }
}
