// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Minor.Dag21.CASServiceClient.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Cursist
    {
        /// <summary>
        /// Initializes a new instance of the Cursist class.
        /// </summary>
        public Cursist() { }

        /// <summary>
        /// Initializes a new instance of the Cursist class.
        /// </summary>
        public Cursist(int cursusInstantieID, string voornaam, string achternaam, int? cursistId = default(int?))
        {
            CursistId = cursistId;
            CursusInstantieID = cursusInstantieID;
            Voornaam = voornaam;
            Achternaam = achternaam;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursistId")]
        public int? CursistId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursusInstantieID")]
        public int CursusInstantieID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "voornaam")]
        public string Voornaam { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "achternaam")]
        public string Achternaam { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Voornaam == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Voornaam");
            }
            if (Achternaam == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Achternaam");
            }
        }
    }
}
