// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Case2.MaRoWo.GarageAdministratie.Infrastructure.Agents.RdwIntegrationService.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class KeuringsVerzoekAntwoord
    {
        /// <summary>
        /// Initializes a new instance of the KeuringsVerzoekAntwoord class.
        /// </summary>
        public KeuringsVerzoekAntwoord() { }

        /// <summary>
        /// Initializes a new instance of the KeuringsVerzoekAntwoord class.
        /// </summary>
        public KeuringsVerzoekAntwoord(bool? isSteekProef = default(bool?), DateTime? steepkProefDate = default(DateTime?))
        {
            IsSteekProef = isSteekProef;
            SteepkProefDate = steepkProefDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isSteekProef")]
        public bool? IsSteekProef { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "steepkProefDate")]
        public DateTime? SteepkProefDate { get; set; }

    }
}
