// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Case2.MaRoWo.GarageAdministratie.Infrastructure.Agents.OnderhoudBeheerService.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class InvalidRequest
    {
        /// <summary>
        /// Initializes a new instance of the InvalidRequest class.
        /// </summary>
        public InvalidRequest() { }

        /// <summary>
        /// Initializes a new instance of the InvalidRequest class.
        /// </summary>
        public InvalidRequest(string message = default(string), IList<string> invalidProperties = default(IList<string>))
        {
            Message = message;
            InvalidProperties = invalidProperties;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "invalidProperties")]
        public IList<string> InvalidProperties { get; set; }

    }
}
