// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Case2.MaRoWo.GarageAdministratie.Infrastructure.Agents.OnderhoudBeheerService.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class OnderhoudAfmeldenCommand
    {
        /// <summary>
        /// Initializes a new instance of the OnderhoudAfmeldenCommand class.
        /// </summary>
        public OnderhoudAfmeldenCommand() { }

        /// <summary>
        /// Initializes a new instance of the OnderhoudAfmeldenCommand class.
        /// </summary>
        public OnderhoudAfmeldenCommand(long onderhoudsId)
        {
            OnderhoudsId = onderhoudsId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "onderhoudsId")]
        public long OnderhoudsId { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
