// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Monument
    {
        /// <summary>
        /// Initializes a new instance of the Monument class.
        /// </summary>
        public Monument() { }

        /// <summary>
        /// Initializes a new instance of the Monument class.
        /// </summary>
        public Monument(long? id = default(long?), string monumentNaam = default(string))
        {
            Id = id;
            MonumentNaam = monumentNaam;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "monumentNaam")]
        public string MonumentNaam { get; set; }

    }
}
